### ISSUE TITLE
Call prismerge without prismerge.json

### ISSUE THREAD

**Issue by beyer-johannes** [prisma-utils/prisma-utils#22]
**Is your feature request related to a problem? Please describe.**

Thanks for your realy helpful tool!

I build a nuxt 3 cli to handle multiple databases, stitched together from multiple schemas based on your prismerge.
To do that, I expect a configuration (`{db1: {inputs: ['/db1/schema.prisma', ...], output: '/db1/schema.merged.prisma', db2: ....}}`), given from anywhere and want to fire the npx prismerge command with that given configuration programmatly with [shelljs](https://github.com/shelljs/shelljs).

Problem:
Prismerge expect a `prismerge.json` given in the directory where `npx prismerge` get called.

To get actually my code works, I need to write a file called `prismerge.json` into my file system and after that call the `npx prismerge` command with shelljs.

Code looks something like that:

```
fs.writeFile(
  './prismerge.json',
  JSON.stringify(options.schemas),
  (error) => {
    if (error) {
      throw error;
    }

    // Stitch schemas
    shelljs.exec(`npx prismerge`);

    // Call other stuff
  }
);
```

**Affected Package**
This is a feature request for which package?
- [ ] nestjs-prisma
- [x] prismerge
- [ ] request-parser

**Describe the solution you'd like**

Simple solution whould be, that the `npx prismerge` command accept an option like `--schema={db1: {inputs: ['/db1/schema.prisma', ...], output: '/db1/schema.merged.prisma', db2: ....}}` which contains the schema.json content json stringified.

**Describe alternatives you've considered**

A realy amazing solution whould be to have access to the prismerge functionality thought the code directly like: 

```
import {prismerge} from 'prismerge';

const schema = {db1: {inputs: ['/db1/schema.prisma', ...], output: '/db1/schema.merged.prisma', db2: ....}};

prismerge.merge(schema);
```

**Additional context**

**Comment by johannesschobel** [comment]
Dear @beyer-johannes ,

not sure if i understood you correctly.
I guess, you need to take a look at the `app` part of `prismerge`, that is described here https://github.com/prisma-utils/prisma-utils/tree/main/libs/prismerge#apps

Because actually, `prismerge` already allows you to define multiple `apps` (in your case, `dbs`).

And, of course, you can call `prismerge` with an optional parameter that tells the cli where the `prismerge.json` (or whatever you would like to call it) is located (i.e., it must not be located at the root level of your project).

```bash
npx prismerge -i ./your/custom/path/to/your/configuration.json
```

should to the trick

All the best

**Comment by beyer-johannes** [comment]
@johannesschobel thanks for you reply.

My problem is, I have no configuration.json located anyhere. I only have a JavaScript variable which contain my configuration. 
Because the configuration is generated at runtime.

Therefore I need to call it like: 
`npx prismerge --schema={db1: {inputs: ['/db1/schema.prisma', ...], output: '/db1/schema.merged.prisma', db2: ....}}`

For more context:
Image a plugin system in a cms. Each plugin comes with his own database schemas. The cms itself as well.
At this moment, I have multple dirs with each schema in it. 
Now if I run `npx myCustomPrismerge` I graph all schemas from all plugins and the schema from the cms and merge it together in one prismerge configuration object. 

With this object I call in runtime from my code `npx prismerge` to let your magic do his job.

Hope it helps to understand my usecase

**Comment by johannesschobel** [comment]
Dear @beyer-johannes ,

thanks for the additional information. However, i think i am still missing a key point here, because it does not make sense.
From your description above, i can imagine that you're developing a CMS. Each plugin (i.e., `news`, `calendar`, ...) has its own directory with its models, views, controllers, ... and its own db schema (i.e., `news.prisma`, `calendar.prisma` files).

Why do you generate the configuration at run-time? Wouldn't it be better to call `prismerge` during development-time? Because you would also need to call `npx prisma generate`, as you would need to create a new prisma client (that is able to properly work with the new schema), and then migrate via `npx prisma migrate`.

Furthermore, doing such database-critical stuff during run-time (without having the possibility to "dry-run") seems kind of odd to me.

> At this moment, I have multple dirs with each schema in it.
> Now if I run npx myCustomPrismerge I graph all schemas from all plugins and the schema from the cms and merge it together in one prismerge configuration object.

I think, this is the part, where i struggle and am not able to properly follow you. If you have the main cms schema file and a lot of other schema files (i.e., one for each module), you can simply create a main prismerge-file like this:

```json
{
  "application" : {
    "inputs": [
      "./path/to/base.schema",
      "./src/app/cms/core.schema",
      "./modules/**/*.schema"
    ],
    "fragments": { ... },
    "output": "./prisma/prisma.schema"
  }
}
```

please note that you are also able to use `globs` (i.e., for the modules) that are resolved when executing the prismerge script.

If you really need this feature, i will be happily adding it. Will need some time though, because i am currently "out of office" ;)

All the best

**Comment by johannesschobel** [comment]
Hey @beyer-johannes , is this still a thing?

**Comment by beyer-johannes** [comment]
@johannesschobel sry. for my late reply. Yes but I needed to stop my project. I will continue it the next months. I'll reopen or create a new ticket if I ran into the same issue. 

Thanks!
