### ISSUE TITLE
moDel camelcase name generation is not implemented for folder names

### ISSUE THREAD

**Issue by ChristopherCapito** [prisma-utils/prisma-utils#37]
**Describe the bug**
If you take a look at the documentation, it provides multiple ways to generate filenames based on your input in the generator options.

One of the options is "moDel" to generate camelcase names. This works for filenames, it does not work for folders. I have looked, and it seems generator.js is missing the following on line 55

"folderPath = folderPath === null || folderPath === void 0 ? void 0 : folderPath.replace(/#{moDel}/g, model.name.charAt(0).toLowerCase() + model.name.slice(1));"

I have added this on my local installation, I can create a pull request for it I think. I have however never contributed code to a library. :D is there anything i need to keep in mind?

kind regards

**Comment by johannesschobel** [comment]
Dear @ChristopherCapito ,

thanks for raising this issue. However, i believe, that this is not strictly needed, because this is mainly needed for `Prisma` models. If you have a model name that is concatenated from 2 words (i.e., `DocumentType`, `UserRole`, ...), the corresponding field in the prisma service is called `userRole` (i.e., the first character is lowercase, all other uppercase characters remain as written).
To properly reflect this, i have created the `moDel` definition that is used throughout the `crud` stub.

For folders, however, i believe, that this naming convention is not really required and suitable (i.e., the folder would be called `userRole`). As this may be required in other scenarios, i will add this later on and provide feedback for you here ;)

All the best and thanks for extensively using these packages here and provide valuable feedback for me!

**Comment by johannesschobel** [comment]
you can try the new version `v 1.2.9` that adds the `#{moDel}` for foldernames!
Can you provide feedback if this works for you?

All the best and thanks a lot

**Comment by ChristopherCapito** [comment]
I have just tried it out. Works like a charm! Thank you.

**Comment by johannesschobel** [comment]
you're welcome.. have fun!
